pip install numpy

- numpy is a python library computing that provides fast and menory-efficient arrays.
- compared to python lists, numpy arrays store same type element and perform mathemeatical operations faster.

In [1]:
import numpy as np

array creation

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [6]:
np.full((5,7),2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [7]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
np.eye(3) #identical matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(3) #random matrix within the range of 0 and 1

array([0.40001789, 0.25065194, 0.33444876])

In [12]:
np.random.randint(10,50, size=(3,3)) #random martix within the range of 10 and 50 

array([[41, 19, 27],
       [47, 37, 24],
       [34, 41, 37]], dtype=int32)

In [13]:
np.array([[1,2,3],[4,5,6]]) #2d array

array([[1, 2, 3],
       [4, 5, 6]])

- [] #id
- [[],[],[]] #2d
- [[[],[]],[[],[]]] #3d

In [14]:
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3d array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]]) #2d array
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Array properties

In [17]:
print(arr.ndim)  # number of dimensions
print(arr.shape) # shape of the array
print(arr.size) #number of element in the array 
print(arr.dtype) #data type of the array 
type(arr) #type of the array

2
(3, 3)
9
int64


numpy.ndarray

reshaping & flattening

In [18]:
arr.reshape(1,9) #reshape the array the array
arr.reshape(9,1) 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [19]:
arr.flatten() #flatten the array 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#iIndexing & slicing 

In [20]:
a[0]
a[1:4]
a[-1]

np.int64(5)